export default [
  {
    title: "Flatiron Building",
    claim: "Unclaimed",
    health: "",
    streak: "",
    button: "Claim Location",
    lat: 40.7411,
    lng: -73.9897,
    url: "https://demo.storj-ipfs.com/ipfs/QmQLoGvgqVnFfJSHT65Po996AWF93svwFKBBHioztwY6qp",
    width: 50,
    height: 50,
  },
  {
    title: "Chelsea Clubhouse",
    claim: "Claimed by: LaunchHouse",
    health: "150 health hearts",
    streak: "Streak: 3 weeks, earning 3x $OLY daily",
    button: "Explore",
    lat: 40.739963376023745,
    lng: -74.00091004484392,
    url: "https://demo.storj-ipfs.com/ipfs/QmQkxRo9mf3mE4ji6hz2aVtt63aQn84yCx3qhVqiMTVvbZ",
    width: 50,
    height: 50,
  },
  {
    title: "Empire State Building",
    claim: "Claimed by: Bored Ape Yacht Club",
    health: "550 health hearts",
    streak: "Streak: 6 months: earning 55x $OLY daily",
    button: "Explore",
    lat: 40.748699610544115,
    lng: -73.98573131600787,
    url: "https://demo.storj-ipfs.com/ipfs/QmUYZmRuwrkcGrDTWDyZehe4HKMfcGi1zo9Aj86DKcrLE9",
    width: 50,
    height: 50,
  },
  {
    title: "Union Square Park",
    claim: "Claimed by: Bored Ape Yacht Club",
    health: "400 health hearts",
    streak: "Streak: 4 months: earning 21x $OLY daily",
    button: "Explore",
    lat: 40.736308135599636,
    lng: -73.99019053532241,
    url: "https://demo.storj-ipfs.com/ipfs/QmUYZmRuwrkcGrDTWDyZehe4HKMfcGi1zo9Aj86DKcrLE9",
    width: 50,
    height: 50,
  },
  {
    title: "The HighLine",
    claim: "Claimed by: Blu3 DAO",
    health: "100 health hearts",
    streak: "Streak: 1 month: earning 5x $OLY daily",
    button: "Explore",
    lat: 40.7480,
    lng: -74.0048,
    url: "https://demo.storj-ipfs.com/ipfs/Qmc169fTVBtU75ZzXT2wve2jXJ17jYH6HhK3eyvSsSf6C4",
    width: 60,
    height: 60,
  },
  {
    title: "Grand Central Terminal",
    claim: "Claimed by: H.E.R. DAO",
    health: "100 health hearts",
    streak: "Streak: 1 month: earning 5x $OLY daily",
    button: "Explore",
    lat: 40.7527,
    lng: -73.9772,
    url: "https://demo.storj-ipfs.com/ipfs/QmYeZRWL96qJFA8yNPQPWNTAtTAyNLkUC568qtu5YDGM8W",
    width: 50,
    height: 25,
  },
  {
    title: "Musuem of Modern Art",
    claim: "Claimed by: BlackLeadersDAO",
    health: "100 health hearts",
    streak: "Streak: 1 month: earning 5x $OLY daily",
    button: "Explore",
    lat: 40.7614,
    lng: -73.9776,
    url: "https://demo.storj-ipfs.com/ipfs/QmSPHeeDLYDEKq4C6C7oumA6awgjHx7MJt4EQKuMwUpuoZ",
    width: 50,
    height: 50,
  },
  {
    title: "The Bowery",
    claim: "Claimed by: Empire DAO",
    health: "250 health hearts",
    streak: "Streak: 2 months: earning 8x $OLY daily",
    button: "Explore",
    lat: 40.7253,
    lng: -73.9903,
    url: "https://demo.storj-ipfs.com/ipfs/Qmaz1q56Bq8cbm5cch3krW94gmAJQTVkfaKfGFAajcXqLp",
    width: 40,
    height: 40,
  },
  {
    title: "Times Square",
    claim: "Claimed by: Snub City",
    health: "350 health hearts",
    streak: "Streak: 3 months: earning 13x $OLY daily",
    button: "Explore",
    lat: 40.7580,
    lng: -73.9855,
    url: "https://demo.storj-ipfs.com/ipfs/QmZeUX67tpkMzoau4NzFqTMys15mhPiVAREstJAKCY8yjb",
    width: 40,
    height: 40,
  },
  {
    title: "Intrepid Sea, Air, and Space Musuem",
    claim: "Claimed by: Cryptolingo DAO",
    health: "10 health hearts",
    streak: "Streak: 1 week, no multiplier",
    button: "Explore",
    lat: 40.7645,
    lng: -73.9996,
    url: "https://demo.storj-ipfs.com/ipfs/QmZ8QwXAq4pqrgfz9Bg3oHZgj7PU9yDCNAa7XLG8dN3KbJ",
    width: 60,
    height: 60,
  },
  {
    title: "Bryant Park",
    claim: "Claimed by: CryptoMujeres DAO",
    health: "10 health hearts",
    streak: "Streak: 1 week, no multiplier",
    button: "Explore",
    lat: 40.7536,
    lng: -73.9832,
    url: "https://demo.storj-ipfs.com/ipfs/QmeJhJU7T42DR8SJBZVRafQjUyEv1grRaxGW3cKFU7HaCy",
    width: 70,
    height: 70,
  },
  {
    title: "Madison Square Garden",
    claim: "Claimed by: HerHouse",
    health: "250 health hearts",
    streak: "Streak: 2 months: earning 8x $OLY daily",
    button: "Explore",
    lat: 40.7505,
    lng: -73.9934,
    url: "https://demo.storj-ipfs.com/ipfs/QmXPxYcUaZwXD7TFhUiSEiHWbWbxY1sEXonJYYoTqSLFsx",
    width: 50,
    height: 50,
  },
  {
    title: "Washington Square Park",
    claim: "Claimed by: Bubble DAO",
    health: "250 health hearts",
    streak: "Streak: 2 months: earning 8x $OLY daily",
    button: "Explore",
    lat: 40.7309,
    lng: -73.9973,
    url: "https://demo.storj-ipfs.com/ipfs/QmXTbFBRciM1tYWwPcAB78dLekvXMD6YpKgJniNTSe6X7B",
    width: 50,
    height: 50,
  },
];
